[build] 
  publish = "dist"
  command = "npm run build"


[dev] 
  publish = "dist"
  command = "npm run dev"


[[redirects]]
  from = "/create"
  to = "/.netlify/functions/save-card"
  status = 200

[[redirects]]
  from = "/card/*"
  to = "/.netlify/builders/view-card"
  status = 200

